### ISSUE TITLE
node-gyp.js windows error

### ISSUE THREAD

**Issue by dhenriet** [auchenberg/remotedebug-gateway#4]
Hi,
I am on windows 8.1, node 5.1.0,
when I launch the installation I have an error with "node-gyp.js". I think I need to install "Visual C++ "VCBuild.exe"" ? (I had same problem with Browser-sync, but I decide to use the comand line instead of gulp)

![screenshot_1](https://cloud.githubusercontent.com/assets/4640027/12887701/7232dc8e-ce76-11e5-81aa-149fb62ae520.png)

**Comment by auchenberg** [comment]
I don't know much about Windows, but this seems to be the solution:
https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

OR

https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

**Comment by mamged** [comment]
@auchenberg also in macOs
`fatal error: too many errors emitted, stopping now [-ferror-limit=]
12 warnings and 20 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/m/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/Users/m/.nvm/versions/node/v9.3.0/bin/node" "/Users/m/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/m/.nvm/versions/node/v9.3.0/lib/node_modules/remotedebug-gateway/node_modules/bufferutil
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> canvas@1.3.16 install /Users/m/.nvm/versions/node/v9.3.0/lib/node_modules/remotedebug-gateway/node_modules/canvas
> node-gyp rebuild

Package zlib was not found in the pkg-config search path.
Perhaps you should add the directory containing `zlib.pc'
to the PKG_CONFIG_PATH environment variable
Package 'zlib', required by 'libpng', not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/m/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/Users/m/.nvm/versions/node/v9.3.0/bin/node" "/Users/m/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/m/.nvm/versions/node/v9.3.0/lib/node_modules/remotedebug-gateway/node_modules/canvas
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.0.1 (node_modules/remotedebug-gateway/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.3.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m/.npm/_logs/2018-03-24T10_38_52_599Z-debug.log`
